<<<<<<< HEAD
# Generated by Django 4.1.7 on 2024-10-18 23:38
=======
# Generated by Django 4.1.7 on 2023-12-20 00:13
>>>>>>> 67d304ea4b40605ad550d744c4b268d28871bcf7

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
<<<<<<< HEAD
import django.utils.timezone
=======
>>>>>>> 67d304ea4b40605ad550d744c4b268d28871bcf7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='FormularioDeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('profesionOcupacion', models.CharField(max_length=30)),
                ('servicioElegido', models.CharField(choices=[('Voluntariado de Base', 'Voluntariado de Base'), ('Candidato a salir al campo', 'Candidato a salir al campo'), ('Intercesion', 'Intercesion'), ('Futuros tutores de HUT', 'Futuros tutores de HUT'), ('Movilizador', 'Movilizador')], max_length=30)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionesMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=50, unique=True)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Icono', models.CharField(max_length=100)),
                ('TipoOpcion', models.IntegerField(choices=[(1, 'Reportes'), (2, 'Eventos'), (3, 'Gráficos')])),
                ('ruta', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> 67d304ea4b40605ad550d744c4b268d28871bcf7
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paisNombre', models.CharField(max_length=100)),
            ],
<<<<<<< HEAD
            options={
                'ordering': ['paisNombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.IntegerField(choices=[(1001, 'Super'), (2002, 'Directivo'), (3003, 'Coordinador'), (111111, 'Desautorizado')])),
            ],
=======
>>>>>>> 67d304ea4b40605ad550d744c4b268d28871bcf7
        ),
        migrations.CreateModel(
            name='ProvinciaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinciaNombre', models.CharField(max_length=100)),
                ('idPais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFormularioInscripcion.pais')),
            ],
        ),
        migrations.CreateModel(
            name='FormularioInscripcionHUT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=25)),
=======
                ('nombre', models.CharField(max_length=60)),
>>>>>>> 67d304ea4b40605ad550d744c4b268d28871bcf7
                ('edad', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(13)])),
                ('ciudad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('congregacion', models.CharField(max_length=50)),
                ('pastor', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('estadoCivil', models.CharField(choices=[('Soltera/o', 'Soltera/o'), ('Casada/o', 'Casada/o')], max_length=9, verbose_name='EstadoCivil')),
<<<<<<< HEAD
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('abandonado', models.BooleanField(default=False)),
                ('fecha_abandono', models.DateTimeField(blank=True, null=True)),
=======
>>>>>>> 67d304ea4b40605ad550d744c4b268d28871bcf7
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFormularioInscripcion.pais')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFormularioInscripcion.provinciaestado')),
            ],
        ),
    ]
