# Generated by Django 4.1.7 on 2023-12-20 00:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paisNombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinciaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinciaNombre', models.CharField(max_length=100)),
                ('idPais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFormularioInscripcion.pais')),
            ],
        ),
        migrations.CreateModel(
            name='FormularioInscripcionHUT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('edad', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(13)])),
                ('ciudad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('congregacion', models.CharField(max_length=50)),
                ('pastor', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('estadoCivil', models.CharField(choices=[('Soltera/o', 'Soltera/o'), ('Casada/o', 'Casada/o')], max_length=9, verbose_name='EstadoCivil')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFormularioInscripcion.pais')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFormularioInscripcion.provinciaestado')),
            ],
        ),
    ]
