# Generated by Django 4.1.7 on 2024-02-19 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularioInscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioinscripcionhut',
            name='abandonado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formularioinscripcionhut',
            name='fecha_abandono',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularioinscripcionhut',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 15, 52, 51, 596135, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
