# Generated by Django 4.1.7 on 2024-10-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularioInscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
