# Generated by Django 4.1.7 on 2024-10-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularioInscripcion', '0002_alter_usuario_password_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='maximiliano93ariel@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
