# Generated by Django 4.1.7 on 2024-02-19 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularioInscripcion', '0002_formularioinscripcionhut_abandonado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioinscripcionhut',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
