# Generated by Django 3.2.25 on 2024-04-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularioInscripcion', '0003_alter_formularioinscripcionhut_fecha_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['paisNombre']},
        ),
        migrations.AddField(
            model_name='formularioinscripcionhut',
            name='apellido',
            field=models.CharField(default='APELLIDO_NUEVO', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formularioinscripcionhut',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
