# Generated by Django 3.2.25 on 2024-05-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularioInscripcion', '0004_auto_20240430_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioDeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('profesionOcupacion', models.CharField(max_length=30)),
                ('servicioElegido', models.CharField(choices=[('Voluntariado de Base', 'Voluntariado de Base'), ('Candidato a salir al campo', 'Candidato a salir al campo'), ('Intercesión', 'Intercesión'), ('Futuros tutores de HUT', 'Futuros tutores de HUT')], max_length=30)),
            ],
        ),
    ]
