# Generated by Django 4.1.7 on 2024-10-23 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularioInscripcion', '0005_usuario_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intentos_fallidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimoIngreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
