# Generated by Django 3.2.25 on 2024-05-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularioInscripcion', '0006_alter_formulariodedecision_servicioelegido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariodedecision',
            name='servicioElegido',
            field=models.CharField(choices=[('Voluntariado de Base', 'Voluntariado de Base'), ('Candidato a salir al campo', 'Candidato a salir al campo'), ('Intercesion', 'Intercesion'), ('Futuros tutores de HUT', 'Futuros tutores de HUT'), ('Movilizador', 'Movilizador')], max_length=30),
        ),
    ]
