# Generated by Django 4.1.7 on 2024-11-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularioInscripcion', '0006_usuario_bloqueado_hasta_usuario_intentos_fallidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionesmenu',
            name='TipoOpcion',
            field=models.IntegerField(choices=[(1, 'Reportes'), (2, 'Formulario'), (3, 'Gráficos')]),
        ),
    ]
