# Generated by Django 4.1.7 on 2024-11-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularioInscripcion', '0007_alter_opcionesmenu_tipoopcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioinscripcionhut',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
