# Generated by Django 4.2.18 on 2025-06-19 04:43

import AppFormularioInscripcion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AppFormularioInscripcion",
            "0008_formularioinscripcionhut_fecha_finalizacion",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaInteres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Voluntario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("apellido", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=20)),
                ("fecha_nacimiento", models.DateField()),
                ("pais_origen", models.CharField(max_length=100)),
                ("pais_residencia", models.CharField(max_length=100)),
                ("provincia_residencia", models.CharField(max_length=100)),
                ("localidad", models.CharField(max_length=100)),
                ("barrio", models.CharField(max_length=100)),
                (
                    "miembro_iglesia",
                    models.CharField(
                        choices=[("SI", "Sí"), ("NO", "No")], max_length=10
                    ),
                ),
                ("cual_iglesia", models.CharField(blank=True, max_length=255)),
                (
                    "sirve_en_iglesia",
                    models.CharField(
                        choices=[("SI", "Sí"), ("NO", "No")], max_length=10
                    ),
                ),
                ("cual_servicio", models.CharField(blank=True, max_length=255)),
                ("tiempo_asistiendo", models.CharField(blank=True, max_length=100)),
                ("contacto_lider", models.CharField(blank=True, max_length=255)),
                (
                    "contacto_lider_telefono",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "voluntario_otra_org",
                    models.CharField(
                        choices=[("SI", "Sí"), ("NO", "No")], max_length=10
                    ),
                ),
                ("cual_org", models.CharField(blank=True, max_length=255)),
                (
                    "hizo_hut",
                    models.CharField(
                        choices=[("SI", "Sí"), ("TODAVIA_NO", "Todavía no")],
                        max_length=20,
                    ),
                ),
                ("hizo_hut_anio", models.CharField(blank=True, max_length=100)),
                (
                    "hizo_reacciona",
                    models.CharField(
                        choices=[("SI", "Sí"), ("TODAVIA_NO", "Todavía no")],
                        max_length=20,
                    ),
                ),
                ("cuando_reacciona", models.CharField(blank=True, max_length=100)),
                (
                    "deseo_salir_campo",
                    models.CharField(
                        choices=[
                            ("SI", "Sí"),
                            ("NO", "No"),
                            ("NO_POR_AHORA", "No por ahora"),
                            ("CORTO_PLAZO", "Por corto plazo"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "nivel_estudio",
                    models.CharField(
                        choices=[
                            ("PRIMARIA_COMPLETA", "Primaria completa"),
                            ("SECUNDARIA_INCOMPLETA", "Secundaria incompleta"),
                            ("SECUNDARIA_COMPLETA", "Secundaria completa"),
                            ("TERCIARIO_INCOMPLETO", "Terciario incompleto"),
                            ("TERCIARIO_COMPLETO", "Terciario completo"),
                            ("UNIVERSITARIO_INCOMPLETO", "Universitario incompleto"),
                            ("UNIVERSITARIO_COMPLETO", "Universitario completo"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titulo_universitario", models.CharField(blank=True, max_length=255)),
                ("cursos_formacion", models.TextField(blank=True)),
                ("experiencia_profesional", models.TextField(blank=True)),
                (
                    "habla_idioma",
                    models.CharField(
                        choices=[("SI", "Sí"), ("NO", "No")], max_length=10
                    ),
                ),
                ("cual_idioma", models.CharField(blank=True, max_length=255)),
                (
                    "lee_escribe_idioma",
                    models.CharField(
                        choices=[("SI", "Sí"), ("NO", "No")], max_length=10
                    ),
                ),
                ("otras_propuestas", models.TextField(blank=True)),
                (
                    "foto_rostro",
                    models.ImageField(
                        upload_to="fotos_rostro/",
                        validators=[
                            AppFormularioInscripcion.models.validar_extension_imagen
                        ],
                    ),
                ),
                (
                    "areas_interes",
                    models.ManyToManyField(
                        blank=True, to="AppFormularioInscripcion.areainteres"
                    ),
                ),
            ],
        ),
    ]
