# Generated by Django 4.2.18 on 2025-10-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppFormularioInscripcion", "0009_areainteres_voluntario"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariodedecision",
            name="telefono",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
